### ISSUE TITLE
Add python script, postman collection or swagger UI link for API Docs Usage

### ISSUE THREAD

**Issue by Soumya44** [mindfiredigital/OpenRAG#1]
We need to improve the developer experience by providing examples and tools for consuming our APIs. Specifically, we would like to:

- Add a Python script demonstrating how to interact with the API.
- Include a Postman collection that contains predefined API requests to make testing easier for developers.
- Provide a link to a Swagger UI that documents all API endpoints and allows users to interact with the API directly from the browser. (Recommended) 

**Requirements**:
1. Create a simple Python script that makes requests to key API endpoints and handles authentication, error handling, and basic responses.
2. Generate a Postman collection with the same API endpoints and proper request/response formats.
3. Add or verify the availability of a Swagger UI link, documenting all API endpoints.

**Acceptance Criteria**:
- Python script and Postman collection are added to the repository under the `/docs` or `/scripts` directory.
- Script and collection are documented clearly in the README with steps on how to use them.
- Swagger UI link is verified and included in the README, if applicable.

**Additional Notes**:
- Ensure that authentication tokens or sensitive data are not hardcoded in the script or collection.
- The script should be modular, allowing easy updates when API endpoints or structures change.

**Comment by abdulla-mindfire** [comment]
Added Postman collection and swagger ui link in readme and mkdocs both
